/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 48;
  /** RegularExpression Id. */
  int ID = 49;
  /** RegularExpression Id. */
  int STRING_LITERAL = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\";\"",
    "\"return\"",
    "\"PRN\"",
    "\"println\"",
    "\"ATTACK\"",
    "\"(\"",
    "\")\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"MOVE\"",
    "\"PICK\"",
    "\"SCAND\"",
    "\"SCANE\"",
    "\"SCANC\"",
    "\"HOME\"",
    "\"WEST\"",
    "\"NWEST\"",
    "\"EAST\"",
    "\"NEAST\"",
    "\"SWEST\"",
    "\"SEAST\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"if\"",
    "\"se\"",
    "\"then\"",
    "\"ent\\u00e3o\"",
    "\"while\"",
    "\"enquanto\"",
    "\"do\"",
    "\"fa\\u00e7a\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<NUM>",
    "<ID>",
    "<STRING_LITERAL>",
  };

}
